SCORING = {
    "pass_yds": 1 / 25,
    "pass_td": 4,
    "pass_int": -2,
    "rush_yds": 1 / 10,
    "rush_td": 6,
    "rec": 1,
    "rec_yds": 1 / 10,
    "rec_td": 5,
    "ret_yds": 1 / 25,
    "ret_td": 6,
    "two_pt": 2,
    "fum_lost": -2,
    "off_fum_td": 6,
    "fg_miss_0_19": -1,
    "fg_miss_20_29": -1,
    "fg_miss_30_39": -1,
    "fg_miss_40_49": -1,
    "fg_miss_50": -1,
    "pat_made": 1,
    "pat_miss": -1,
    "fg_yds": 1 / 10,
    "sack": 1,
    "dst_int": 2,
    "dst_fum_rec": 2,
    "dst_td": 6,
    "dst_safety": 2,
    "dst_block_kick": 2,
    "dst_ret_td": 6,
    "dst_pa_0": 10,
    "dst_pa_1_6": 7,
    "dst_pa_7_13": 4,
    "dst_pa_14_20": 1,
    "dst_pa_21_27": 0,
    "dst_pa_28_34": -1,
    "dst_pa_35_plus": -4,
    "dst_xp_ret": 2,
}

LINEUP = [
    ("QB", 1),
    ("RB", 2),
    ("WR", 2),
    ("TE", 1),
    ("FLEX", 1),  # W/R/T
    ("K", 1),
    ("DEF", 1),
    ("BN", 5),
]

POSITIONS = ["QB", "RB", "WR", "TE", "K", "DEF"]
